Revert "Revert "Homework 1""
TimofeyImaev/Tinkoff_Java pull request #9
Opened 2023-10-11 05:49 UTC by TimofeyImaev

Reverts TimofeyImaev/Tinkoff_Java#4

2023-10-11 16:17 UTC, kkkoltunov requested changes

2023-10-11 16:17 UTC, kkkoltunov commented on src/main/java/edu/hw1/ConstantKaprekala.java
> +public class ConstantKaprekala {
давай сразу везде договоримся именовать классы по номеру задания, например `Task1`

2023-10-11 16:17 UTC, kkkoltunov commented on src/main/java/edu/hw1/CountDigits.java
> +        final int TEN = 10;
давай выносить подобные переменные в константы класса 
```
public class CountDigits {
    private final static Logger LOGGER = LogManager.getLogger();
    private final static Integer TEN_NUMBER = 10;
```

2023-10-11 16:17 UTC, kkkoltunov commented on src/main/java/edu/hw1/CountDigits.java
> +        final int TEN = 10;
поправь это пожалуйста и в остальных задачах

2023-10-11 16:17 UTC, kkkoltunov commented on src/main/java/edu/hw1/IsNestable.java
> +            minArr1 = each < minArr1 ? each : minArr1;
можно пользоваться функциями min и max, и сделать сильно проще
```
Math.min(each, minArr1);
```

2023-10-11 16:17 UTC, kkkoltunov commented on src/main/java/edu/hw1/KnightBoardCapture.java
> +        Pair<Integer, Integer>[] coords = new Pair[] {
давай стараться давать более осмысленные названия переменным, понимаю что это задачки чисто на логику и базовые общие знания, но все же так будет более понятно

2023-10-11 16:17 UTC, kkkoltunov commented on src/main/java/edu/hw1/Pair.java
> +public class Pair<A, B> {
это ты конечно классно придумал)))

2023-10-11 16:17 UTC, kkkoltunov commented on src/test/java/edu/hw1/ConstantKaprekalaTest.java
> +    void basicTest1() {
давай давать более осмысленное название тестам в формате `testThat...Returned...`

2023-10-11 16:17 UTC, kkkoltunov commented on src/test/java/edu/hw1/ConstantKaprekalaTest.java
> +    @DisplayName("Базовый тест1")
тут тоже желательно писать что именно тест проверяет, чтобы было более понятно, иначе смысл от этих анноташек?

2023-10-11 16:17 UTC, kkkoltunov commented on src/test/java/edu/hw1/ConstantKaprekalaTest.java
> +    @DisplayName("Базовый тест1")
поправь пожалуйста везде

2023-10-11 16:17 UTC, kkkoltunov commented on src/test/java/edu/hw1/specialPalindromeTest.java
> +public class specialPalindromeTest {
названия класса пишем с большой буквы

2023-10-11 16:17 UTC, kkkoltunov commented on src/test/java/edu/hw1/NestedArrTest.java
> +public class NestedArrTest {
пользуйся пожалуйста автоформатированием кода, в каждом отдельном классе можно нажимать специальные хоткеи и код будет форматироваться

еще можно кликать ПКМ на весь пакет и нажимать `Reformat Code` и все классы будут форматироваться

2023-10-11 16:17 UTC, kkkoltunov commented on src/test/java/edu/hw1/ConstantKaprekalaTest.java
> +public class ConstantKaprekalaTest {
тесты аналогично давай именовать по порядку заданий

2023-10-12 16:49 UTC, TimofeyImaev commented on src/main/java/edu/hw1/ConstantKaprekala.java
> +public class ConstantKaprekala {
Пронумеровал все классы.

2023-10-12 16:50 UTC, TimofeyImaev commented on src/main/java/edu/hw1/CountDigits.java
> +        final int TEN = 10;
Всё сделал, теперь они выглядят как константы

2023-10-12 16:50 UTC, TimofeyImaev commented on src/main/java/edu/hw1/KnightBoardCapture.java
> +        Pair<Integer, Integer>[] coords = new Pair[] {
Поменял название массива пар.

2023-10-12 16:51 UTC, TimofeyImaev commented on src/main/java/edu/hw1/IsNestable.java
> +            minArr1 = each < minArr1 ? each : minArr1;
Написал функции, теперь код выглядит очень понятно.

2023-10-12 16:52 UTC, TimofeyImaev commented on src/main/java/edu/hw1/Pair.java
> +public class Pair<A, B> {
Спасибо, вообще интересно как это нормально сделать. Если вам не сложно, объясните мне в ответе на пр или в телеграме @boberxa4

2023-10-12 16:52 UTC, TimofeyImaev commented on src/test/java/edu/hw1/ConstantKaprekalaTest.java
> +    void basicTest1() {
Я сделал, только все тесты я называл на русском, хочу в следующем дз давать названия на английском.

2023-10-12 16:53 UTC, TimofeyImaev commented on src/test/java/edu/hw1/ConstantKaprekalaTest.java
> +    @DisplayName("Базовый тест1")
Было тяжело, но поправил везде.

2023-10-12 16:53 UTC, TimofeyImaev commented on src/test/java/edu/hw1/specialPalindromeTest.java
> +public class specialPalindromeTest {
Поменял.

2023-10-12 16:53 UTC, TimofeyImaev commented on src/test/java/edu/hw1/NestedArrTest.java
> +public class NestedArrTest {
Я нажал ctrl + alt + L во всех файлах.

2023-10-12 16:54 UTC, TimofeyImaev commented on src/test/java/edu/hw1/ConstantKaprekalaTest.java
> +public class ConstantKaprekalaTest {
Тесты тоже переименовал.

2023-10-12 17:25 UTC, kkkoltunov commented
молодец, хорошая работа! единственный нюанс, не закрывай треды пока я их не прочитаю, я сделаю это сам, а если они закрываются сами, то открывай их пожалуйста

2023-10-12 17:25 UTC, merged